name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Downnload go@v1.13.8
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.8
        
    - name: Checkout repo
      uses: actions/checkout@v1
      
    - name: Download deps
      run: go mod download

    - name: Test
      run: go test -v -race ./...
